node {
    stage ("Checkout DataService"){
        git url: 'https://github.com/dipendrashrestha1281/teamCDproject.git'
    }
    
    stage ("Gradle Build - DataService") {
        sh 'gradle -b teamCDmccdataservice/build.gradle clean build'
    }
    
    stage ("Gradle Bootjar-Package - DataService") {
        sh 'gradle -b teamCDmccdataservice/build.gradle bootjar'
    }
    
    stage('User Acceptance Test - DataService') {
	
	  def response= input message: 'Is this build good to go?',
	   parameters: [choice(choices: 'Yes\nNo', 
	   description: '', name: 'Pass')]
	
	  if(response=="Yes") {
	    stage('Release - DataService') {
	      sh 'gradle -b teamCDmccdataservice/build.gradle -x test'
	      sh 'echo Release this version'
	    }
	  }
    }
}